global:
  resolve_timeout: 5m

route:
  group_by: ['alertname','serverity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'ENV_ALERT_WEB_HOOK'
